language: php

addons:
  code_climate:
    repo_token: "cda80f594af9de8ba18b3c241b9bd0c47194cbc258c743abe05a81d8576fc702"

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

matrix:
  allow_failures:
    - php: '5.4'
    - php: '5.5'
    - php: 'nightly'

install:
  - composer install

script:
  - composer travis

after_script:
  - ./vendor/bin/test-reporter
