language: php

addons:
  code_climate:
    repo_token: "9fd3109ab8b2555fd4f263d49d9884274ff952e2149f9bf45103c67ccfe77492"

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

matrix:
  allow_failures:
    - php: '5.4'
    - php: '5.5'
    - php: 'nightly'

install:
  - composer install

script:
  - composer travis

after_script:
  - ./vendor/bin/test-reporter
